# Немецкий языковой пакет
started = "[+]TelegaServer startet"
enter_token = "Geben Sie den Token ein, der im Bot verwendet werden soll: "
enter_passwd_set = "Geben Sie das Passwort ein, das im Bot verwendet wird: "
file_configured = "Datei erfolgreich konfiguriert"
press_c = "  DRÜCKEN SIE STRG+C ZUM BEENDEN                                                                              "
fail_started = "Bot konnte nicht gestartet werden :("
welcome = "Willkommen, {0.first_name}!\nIch bin Ihr Computer.\n/auth – Authentifizierung auf dem Server\n/system – ermöglicht Zugriff auf den Server.\nWeitere Details zu Bot-Befehlen in der Dokumentation."
enter_passwd = "Geben Sie zur Authentifizierung das Passwort vom Server ein."
auth_success = "Die Authentifizierung war erfolgreich."
wrong_pass = "Falsches Passwort"
enter_comm = "Geben Sie einen Befehl ein."
no_access = "Sie haben keinen Zugriff."
select_file_down = "Wählen Sie aus diesem Verzeichnis die Datei aus, die Sie herunterladen möchten."
select_file_up = "Wählen Sie die Datei aus, die Sie in dieses Verzeichnis hochladen möchten."
err_comm = "Beim Ausführen des Befehls ist ein Fehler aufgetreten. Fehlercode: "
err_cd = "Beim Ändern des Verzeichnisses ist ein Fehler aufgetreten. Möglicherweise haben Sie den Pfad nicht richtig angegeben."
err_sand_file = "Beim Senden der Datei ist ein Fehler aufgetreten. Bitte überprüfen Sie den Dateinamen."
file_save_in = "Die Datei wurde erfolgreich im Verzeichnis gespeichert "
disconnect = "Verbindung zum Server wird getrennt..."
err_init = "Fehler beim Initialisieren des Bots."

timeout_60 = "Timeout 1 Minute..."
