# Испанский языковой пакет
started = "[+]Comienza TelegaServer"
enter_token = "Ingrese el token que se usará en el bot: "
enter_passwd_set = "Introduzca la contraseña que se utilizará en el bot: "
file_configured = "Archivo configurado correctamente"
press_c = "  PRESIONA CTRL+C PARA SALIR                                                                                  "
fail_started = "No se pudo iniciar el bot :("
welcome = "¡Bienvenido, {0.first_name}!\nSoy tu computadora.\n/auth: autenticación en el servidor\n/sistema: brinda acceso al servidor.\nMás detalles sobre los comandos del bot en la documentación."
enter_passwd = "Introduzca la contraseña del servidor para la autenticación."
auth_success = "La autenticación fue exitosa."
wrong_pass = "Contraseña incorrecta"
enter_comm = "Introduce un comando."
no_access = "No tienes acceso."
select_file_down = "Seleccione el archivo que desea descargar de este directorio."
select_file_up = "Seleccione el archivo que desea cargar en este directorio."
err_comm = "Ocurrió un error al ejecutar el comando. Código de error: "
err_cd = "Hubo un error al cambiar el directorio, puede que no hayas especificado la ruta correctamente."
err_sand_file = "Error al enviar el archivo, verifique el nombre del archivo."
file_save_in = "El archivo se guardó correctamente en el directorio "
disconnect = "Desconectando del servidor..."
err_init = "Error al inicializar el bot."

timeout_60 = "Tiempo de espera 1 minuto..."
